
Route.create!([
  {ruta: "Teusaquillo"},
  {ruta: "Chico Norte"},
  {ruta: "Circunvalar"},
  {ruta: "Centro"},
  {ruta: "Americas"}
])

Client.create!([
  {name: "Lebsack, Yost and Hermiston", email: "hayden.koch@veumdoyle.org", address: "434 Daren Springfil", phone: 8057325, route_id: 1},
  {name: "Zboncak LLC", email: "palma@rolfson.biz", address: "491 Kihn Pines", phone: 6625510, route_id: 4},
  {name: "Rohan-Sauer", email: "talia@brakusheaney.co", address: "90122 Rowan Mall", phone: 7619717, route_id: 1},
  {name: "Heller, Greenholt and Bashirian", email: "daron_ryan@corwinschowalter.io", address: "19977 Boyer Courts", phone: 8857767, route_id: 4},
  {name: "Funk-Skiles", email: "grayson@willms.biz", address: "7841 Klein Port", phone: 5815294, route_id: 2},
  {name: "Gerhold, Nolan and Fisher", email: "geovanni@schamberger.info", address: "902 Parisian Haven", phone: 6429776, route_id: 3},
  {name: "Hauck, Glover and Kilback", email: "caie@heathcote.biz", address: "89859 Jessika Vista", phone: 5823152, route_id: 4},
  {name: "Pfeffer and Sons", email: "felipa.boyle@quigley.net", address: "5645 Cooper Land", phone: 6471554, route_id: 5},
  {name: "Schimmel LLC", email: "callie_price@mooreko.co", address: "804 Hoeger Parks", phone: 6967592, route_id: 1},
  {name: "Kling Group", email: "jody_hilll@cain.info", address: "19499 Moore Shoal", phone: 7711323, route_id: 4},
  {name: "O'Keefe Group", email: "christy.jones@borer.org", address: "15696 Langworth Forks", phone: 8437690, route_id: 5},
  {name: "Spinka-Bins", email: "adaline.walsh@bernhardkilback.io", address: "97566 Beatty Shore", phone: 7947169, route_id: 4},
  {name: "Schamberger-Waters", email: "madonna.kuhic@nikolausleffler.com", address: "1306 Avis Corners", phone: 6262031, route_id: 3},
  {name: "Barton, Feil and Eichmann", email: "frieda@jakubowski.com", address: "436 Wallace Well", phone: 8575751, route_id: 4},
  {name: "Dibbert and Sons", email: "arjun_mraz@heidenreich.net", address: "3123 Reginald Center", phone: 6869425, route_id: 4},
  {name: "Borer, Ullrich and Casper", email: "magdalena_turcotte@emmerich.com", address: "2386 Connelly Dale", phone: 8561163, route_id: 1},
  {name: "Wintheiser, Veum and Kilback", email: "tevin@parkerkihn.biz", address: "604 Klein Brooks", phone: 6240502, route_id: 1},
  {name: "Marks, Stokes and Connelly", email: "ladarius@beahan.com", address: "32839 VonRueden Village", phone: 6170358, route_id: 2},
  {name: "Schoen, Spencer and Muller", email: "jee_bailey@stammklocko.com", address: "40239 Frederique Pass", phone: 8819626, route_id: 5},
  {name: "Graham-Kunde", email: "winston_olson@howe.org", address: "429 Walter Meadow", phone: 6437554, route_id: 4},
  {name: "Daniel-Kshlerin", email: "janae.treutel@schaefer.org", address: "5898 Bosco Ville", phone: 8276259, route_id: 1},
  {name: "Funk, Howe and Berge", email: "chanelle@wuckert.name", address: "2249 Nolan Way", phone: 8364849, route_id: 3},
  {name: "Dare-Jakubowski", email: "oceane.sipes@lockman.co", address: "170 Dewayne Summit", phone: 6038541, route_id: 5},
  {name: "Doyle-Larson", email: "angelo_kautzer@hegmann.net", address: "22689 Hanna Throughway", phone: 8830999, route_id: 4},
  {name: "Goodwin-Ondricka", email: "luciano@gerhold.io", address: "879 Alvera Harbors", phone: 6635942, route_id: 2},
  {name: "Rippin-Marks", email: "ted.cronin@schusterlabadie.biz", address: "46995 Hamill Parks", phone: 8072433, route_id: 4},
  {name: "Bednar LLC", email: "blanca@dickinson.biz", address: "895 Ceasar Fort", phone: 7453172, route_id: 5},
  {name: "Labadie LLC", email: "gail_oberbrunner@harber.org", address: "118 Schmitt Flats", phone: 8235354, route_id: 5},
  {name: "Hilpert LLC", email: "maxine@purdyhickle.com", address: "23752 Aileen Wells", phone: 5914318, route_id: 4},
  {name: "Schiller-Little", email: "lelia.wiegand@sanford.info", address: "22867 Daryl Ford", phone: 6733511, route_id: 4},
  {name: "Gerlach Group", email: "alisha_shanahan@littel.co", address: "5755 Bailey Gardens", phone: 5982782, route_id: 3},
  {name: "Lynch, Haley and Kovacek", email: "willard_fisher@blick.info", address: "58754 Thad Gardens", phone: 6336691, route_id: 3},
  {name: "Doyle Group", email: "adella@effertz.info", address: "55398 Kerluke Hill", phone: 7339602, route_id: 3},
  {name: "Davis-Lueilwitz", email: "orlo_schmeler@zulaufreichel.net", address: "970 Cummerata Route", phone: 6927126, route_id: 2},
  {name: "Kuvalis LLC", email: "reanna_durgan@kautzer.co", address: "3062 Homenick Isle", phone: 8768161, route_id: 1},
  {name: "Crona Group", email: "mona@gulgowski.info", address: "30710 Oran Plains", phone: 7557975, route_id: 3},
  {name: "Cassin and Sons", email: "maxine@marvin.io", address: "6609 Jannie Lakes", phone: 7332423, route_id: 5},
  {name: "Hodkiewicz-Nienow", email: "courtney_powlowski@cremin.net", address: "587 Willis Flat", phone: 6065572, route_id: 3},
  {name: "Borer Inc", email: "cristobal@smith.org", address: "9257 Elyse Canyon", phone: 7366635, route_id: 3},
  {name: "Schiller Inc", email: "moses.schultz@nader.io", address: "2568 Bergstrom Light", phone: 7816608, route_id: 1},
  {name: "Hintz, Reichel and Weimann", email: "piper_hegmann@moorestokes.org", address: "4472 Homenick Road", phone: 8401599, route_id: 5},
  {name: "Heller, Keebler and Rodriguez", email: "karolann.blick@auer.name", address: "7566 Roberto Locks", phone: 8890814, route_id: 3},
  {name: "Murazik-Wolf", email: "sister@ernsersporer.com", address: "733 O'Conner Trail", phone: 8768034, route_id: 5},
  {name: "White and Sons", email: "thora_murphy@rathmarvin.name", address: "8789 Powlowski Harbors", phone: 5815045, route_id: 3},
  {name: "Hettinger Group", email: "kellie.altenwerth@west.net", address: "345 Reilly Vista", phone: 8192776, route_id: 3},
  {name: "Mueller-Hagenes", email: "destini_brakus@harriscollins.org", address: "10982 Herminia Throughway", phone: 8571084, route_id: 4},
  {name: "Williamson and Sons", email: "narciso_mohr@bergnaummonahan.org", address: "55761 Makayla Lake", phone: 8520535, route_id: 3},
  {name: "Kutch, Gutmann and Carter", email: "jaclyn@kemmer.co", address: "2399 Jast Pike", phone: 6686991, route_id: 4},
  {name: "Lehner and Sons", email: "augustine@gaylord.biz", address: "9925 Weimann Flat", phone: 6875334, route_id: 4},
  {name: "Lang Group", email: "monroe@weimann.com", address: "1186 Koepp Mountains", phone: 6539562, route_id: 5},
  {name: "Senger-Cummings", email: "alexandra@luettgen.info", address: "8680 Katlyn Corner", phone: 7937648, route_id: 1},
  {name: "Little Inc", email: "avis@boyer.co", address: "270 Donnelly Parkways", phone: 8807782, route_id: 2},
  {name: "Reichert-Pfeffer", email: "jerry@tillman.co", address: "247 Kade Lodge", phone: 7573903, route_id: 5},
  {name: "Emard-Hyatt", email: "abe.bednar@olson.com", address: "71100 Lorena Camp", phone: 8863102, route_id: 4},
  {name: "Skiles-Goyette", email: "khalid@skilesankunding.biz", address: "708 Baron Valley", phone: 7969281, route_id: 1},
  {name: "Dickens, Roob and Gutmann", email: "crystel@hamillskiles.io", address: "71988 Kub Courts", phone: 5944014, route_id: 1},
  {name: "Lemke, Vandervort and Willms", email: "laurianne.hoeger@king.co", address: "124 Padberg Inlet", phone: 7233537, route_id: 3},
  {name: "Homenick, Kuhn and Schroeder", email: "ben_walker@caspercummings.name", address: "374 Litzy Islands", phone: 7881505, route_id: 3},
  {name: "Sanford Group", email: "alvera_gleichner@braun.com", address: "94073 Stroman Flat", phone: 6391239, route_id: 5},
  {name: "Von and Sons", email: "dayton@kozeymacejkovic.co", address: "3648 Norbert Streets", phone: 6283410, route_id: 3},
  {name: "Ryan Group", email: "carolyn@krajcik.org", address: "991 Peggie Unions", phone: 8520971, route_id: 1},
  {name: "Howell-DuBuque", email: "zelma.stark@ebertsauer.com", address: "957 Tia Falls", phone: 8363138, route_id: 1},
  {name: "Luettgen-McKenzie", email: "andreane@dicki.co", address: "512 Burley Heights", phone: 8270563, route_id: 1},
  {name: "Kemmer Group", email: "hertha@murphy.name", address: "127 Oma Coves", phone: 7284352, route_id: 4},
  {name: "Morissette-Kutch", email: "sincere.gerhold@torphyolson.com", address: "2133 Durward Oval", phone: 7176127, route_id: 1},
  {name: "Weimann, Conn and O'Conner", email: "halie@bergstromkub.biz", address: "468 Romaguera Overpass", phone: 6842252, route_id: 2},
  {name: "Schmidt Inc", email: "desiree.boyle@mitchellheidenreich.co", address: "3079 Jerde Mountain", phone: 6838122, route_id: 4},
  {name: "Jacobson Inc", email: "felton@uptondaugherty.info", address: "90098 Emard Meadows", phone: 6096884, route_id: 5},
  {name: "Mitchell and Sons", email: "americo.keler@monahancarter.co", address: "391 Annette Overpass", phone: 6439725, route_id: 2},
  {name: "Funk, Kunze and Wyman", email: "gabriella.balistreri@bailey.co", address: "305 Franecki Crescent", phone: 8778264, route_id: 4},
  {name: "Rempel, Skiles and Wuckert", email: "jarrell_lowe@ryan.co", address: "955 Ova Parks", phone: 7876588, route_id: 3},
  {name: "Abbott, Hauck and Kunde", email: "reie@hudsonparker.co", address: "2081 Jerrod Lights", phone: 6200109, route_id: 2},
  {name: "Kemmer, Nicolas and Larkin", email: "tavares_cruickshank@bednar.com", address: "5616 Aiyana Passage", phone: 7236553, route_id: 1},
  {name: "Kutch LLC", email: "aubree_jakubowski@daniel.io", address: "650 Rodriguez Lights", phone: 5883314, route_id: 4},
  {name: "Funk Group", email: "jordan@moriette.info", address: "14594 Jovanny Lock", phone: 8174968, route_id: 5},
  {name: "Renner-Hoeger", email: "julie_weber@lind.biz", address: "680 Murazik Mountains", phone: 7835943, route_id: 4},
  {name: "Hagenes-Kohler", email: "leonardo.trantow@balistreri.com", address: "14081 Mikel Landing", phone: 8152096, route_id: 5},
  {name: "Schmidt Group", email: "jordi_fahey@kuvalisoberbrunner.net", address: "3286 Hartmann Isle", phone: 8275452, route_id: 4},
  {name: "Williamson-Block", email: "dannie.jakubowski@bradtkehermann.org", address: "4431 Terrell Mountain", phone: 6799799, route_id: 5},
  {name: "Ebert, Bogisich and Friesen", email: "claire@pouros.net", address: "560 Koch Fall", phone: 6835345, route_id: 1},
  {name: "Larson, Ledner and Bernier", email: "adrien@kelerluettgen.co", address: "9752 Powlowski Island", phone: 6368505, route_id: 2},
  {name: "Reynolds, Harber and Collins", email: "gaetano@gusikowski.name", address: "510 Huels Junctions", phone: 7245775, route_id: 3},
  {name: "McKenzie, Keebler and Walker", email: "earlene_boyer@frami.io", address: "623 Sierra Gateway", phone: 6694718, route_id: 1},
  {name: "Kub and Sons", email: "brandyn@reinger.io", address: "75019 Johathan Crescent", phone: 7200480, route_id: 1},
  {name: "Metz, Kling and Goodwin", email: "irma_bartoletti@kuvalis.com", address: "80312 Joaquin Key", phone: 7982754, route_id: 2},
  {name: "Osinski Group", email: "eino_eichmann@aufderhar.com", address: "248 Sarina Turnpike", phone: 5816909, route_id: 4},
  {name: "Howe, Hickle and Wunsch", email: "estell.lesch@torphy.net", address: "2406 Breitenberg Passage", phone: 6593647, route_id: 4},
  {name: "Stamm-Bahringer", email: "matilde.stokes@moore.name", address: "826 Oma Crossroad", phone: 8509606, route_id: 3},
  {name: "Heathcote-Kreiger", email: "ahmed_eichmann@beer.biz", address: "873 Spinka Loaf", phone: 8451659, route_id: 1},
  {name: "Jacobi, Wunsch and Quitzon", email: "elya@daredooley.info", address: "80825 Arlie Valleys", phone: 6763397, route_id: 1},
  {name: "Watsica-Schamberger", email: "maude_denesik@breitenbergschumm.biz", address: "674 Daniel Wall", phone: 7754371, route_id: 5},
  {name: "Gibson, Swift and McClure", email: "karelle.crist@zulaufbruen.io", address: "65087 Ortiz Inlet", phone: 7791161, route_id: 5},
  {name: "Dickens-Fritsch", email: "emmet@shanahanleuschke.co", address: "334 Naomi Rapids", phone: 7702559, route_id: 5},
  {name: "Predovic Group", email: "uriel_wilkinson@homenick.name", address: "944 Frami Track", phone: 8804155, route_id: 4},
  {name: "Lockman-Corkery", email: "name.bergnaum@kutch.net", address: "38620 Leo Trail", phone: 7723160, route_id: 4},
  {name: "Beer, Wehner and Dare", email: "sydnie.schiller@wolf.name", address: "702 Marisol Alley", phone: 8618385, route_id: 1},
  {name: "Ondricka and Sons", email: "emely.rice@streichgraham.co", address: "877 Ruthe Junction", phone: 7904438, route_id: 3},
  {name: "Daugherty Inc", email: "jarret@stamm.io", address: "5916 Bernier Street", phone: 7623558, route_id: 4},
  {name: "Schamberger, Bogan and Koch", email: "ward_stanton@krismante.io", address: "39560 Hayes Burgs", phone: 7292303, route_id: 5},
  {name: "Swift-Murphy", email: "annalise_schinner@padbergferry.co", address: "660 David Ridge", phone: 8158202, route_id: 3}
])
Receipt.create!([
  {client_id: 85, amount: 153000, user_id: 5, temperature: 21},
  {client_id: 7, amount: 129000, user_id: 5, temperature: 4},
  {client_id: 66, amount: 45000, user_id: 7, temperature: 22},
  {client_id: 44, amount: 103000, user_id: 5, temperature: 15},
  {client_id: 96, amount: 139000, user_id: 5, temperature: 19},
  {client_id: 92, amount: 111000, user_id: 6, temperature: 21},
  {client_id: 50, amount: 59000, user_id: 7, temperature: 21},
  {client_id: 1, amount: 137000, user_id: 7, temperature: 21},
  {client_id: 54, amount: 79000, user_id: 7, temperature: 12},
  {client_id: 58, amount: 10000, user_id: 5, temperature: 7},
  {client_id: 21, amount: 118000, user_id: 6, temperature: 11},
  {client_id: 35, amount: 125000, user_id: 6, temperature: 5},
  {client_id: 44, amount: 156000, user_id: 7, temperature: 15},
  {client_id: 100, amount: 114000, user_id: 5, temperature: 20},
  {client_id: 99, amount: 164000, user_id: 7, temperature: 20},
  {client_id: 16, amount: 13000, user_id: 5, temperature: 2},
  {client_id: 72, amount: 181000, user_id: 7, temperature: 25},
  {client_id: 5, amount: 135000, user_id: 7, temperature: 2},
  {client_id: 2, amount: 71000, user_id: 7, temperature: 2},
  {client_id: 27, amount: 189000, user_id: 5, temperature: 12},
  {client_id: 60, amount: 163000, user_id: 6, temperature: 20},
  {client_id: 26, amount: 54000, user_id: 7, temperature: 19},
  {client_id: 63, amount: 54000, user_id: 6, temperature: 24},
  {client_id: 98, amount: 18000, user_id: 5, temperature: 10},
  {client_id: 50, amount: 31000, user_id: 7, temperature: 6},
  {client_id: 99, amount: 25000, user_id: 6, temperature: 13},
  {client_id: 58, amount: 62000, user_id: 6, temperature: 16},
  {client_id: 47, amount: 11000, user_id: 7, temperature: 11},
  {client_id: 47, amount: 59000, user_id: 6, temperature: 23},
  {client_id: 38, amount: 133000, user_id: 5, temperature: 14}
])

Sample.create!([
  {sample: "glucosa", quantity: 17, receipt_id: 12},
  {sample: "sangre", quantity: 17, receipt_id: 13},
  {sample: "plasma", quantity: 19, receipt_id: 27},
  {sample: "plasma", quantity: 4, receipt_id: 5},
  {sample: "plasma", quantity: 16, receipt_id: 23},
  {sample: "sangre", quantity: 6, receipt_id: 2},
  {sample: "sangre", quantity: 14, receipt_id: 27},
  {sample: "fluido", quantity: 7, receipt_id: 17},
  {sample: "fluido", quantity: 11, receipt_id: 9},
  {sample: "plasma", quantity: 18, receipt_id: 15},
  {sample: "sangre", quantity: 8, receipt_id: 12},
  {sample: "glucosa", quantity: 11, receipt_id: 2},
  {sample: "fluido", quantity: 13, receipt_id: 19},
  {sample: "sangre", quantity: 5, receipt_id: 5},
  {sample: "glucosa", quantity: 20, receipt_id: 3},
  {sample: "sangre", quantity: 18, receipt_id: 24},
  {sample: "fluido", quantity: 17, receipt_id: 4},
  {sample: "plasma", quantity: 13, receipt_id: 13},
  {sample: "fluido", quantity: 2, receipt_id: 16},
  {sample: "fluido", quantity: 7, receipt_id: 26},
  {sample: "plasma", quantity: 13, receipt_id: 29},
  {sample: "plasma", quantity: 14, receipt_id: 4},
  {sample: "sangre", quantity: 7, receipt_id: 29},
  {sample: "glucosa", quantity: 18, receipt_id: 4},
  {sample: "sangre", quantity: 6, receipt_id: 17},
  {sample: "fluido", quantity: 20, receipt_id: 22},
  {sample: "plasma", quantity: 18, receipt_id: 1},
  {sample: "fluido", quantity: 14, receipt_id: 5},
  {sample: "glucosa", quantity: 10, receipt_id: 27},
  {sample: "plasma", quantity: 7, receipt_id: 12},
  {sample: "fluido", quantity: 12, receipt_id: 16},
  {sample: "plasma", quantity: 11, receipt_id: 11},
  {sample: "glucosa", quantity: 3, receipt_id: 9},
  {sample: "plasma", quantity: 7, receipt_id: 10},
  {sample: "sangre", quantity: 11, receipt_id: 4},
  {sample: "plasma", quantity: 19, receipt_id: 25},
  {sample: "glucosa", quantity: 13, receipt_id: 22},
  {sample: "glucosa", quantity: 13, receipt_id: 30},
  {sample: "plasma", quantity: 14, receipt_id: 30},
  {sample: "fluido", quantity: 5, receipt_id: 14},
  {sample: "plasma", quantity: 20, receipt_id: 2},
  {sample: "plasma", quantity: 16, receipt_id: 9},
  {sample: "plasma", quantity: 17, receipt_id: 3},
  {sample: "fluido", quantity: 1, receipt_id: 29},
  {sample: "sangre", quantity: 20, receipt_id: 23},
  {sample: "fluido", quantity: 3, receipt_id: 20},
  {sample: "glucosa", quantity: 19, receipt_id: 17},
  {sample: "fluido", quantity: 1, receipt_id: 6},
  {sample: "fluido", quantity: 18, receipt_id: 1},
  {sample: "plasma", quantity: 14, receipt_id: 26},
  {sample: "plasma", quantity: 19, receipt_id: 30},
  {sample: "glucosa", quantity: 3, receipt_id: 5},
  {sample: "fluido", quantity: 7, receipt_id: 8},
  {sample: "sangre", quantity: 3, receipt_id: 19},
  {sample: "fluido", quantity: 19, receipt_id: 3},
  {sample: "glucosa", quantity: 13, receipt_id: 7},
  {sample: "sangre", quantity: 18, receipt_id: 9},
  {sample: "fluido", quantity: 11, receipt_id: 24},
  {sample: "glucosa", quantity: 19, receipt_id: 28},
  {sample: "plasma", quantity: 4, receipt_id: 22},
  {sample: "sangre", quantity: 12, receipt_id: 1},
  {sample: "fluido", quantity: 11, receipt_id: 11},
  {sample: "glucosa", quantity: 3, receipt_id: 13},
  {sample: "glucosa", quantity: 10, receipt_id: 1},
  {sample: "sangre", quantity: 19, receipt_id: 18},
  {sample: "glucosa", quantity: 4, receipt_id: 21}
])
